### ISSUE TITLE
Tracking: Bot Kit Pro Extensions for High Volume Publishers

### ISSUE THREAD

**Issue by bwcDvorak** [xmtp/xmtp-node-js-tools#203]
- [x] [Original thread/discussion](https://xmtp-labs.slack.com/archives/C06QVLCR8E9/p1711473439535609)
- [ ] Demonstrate how to adopt GRPC
- [ ] Drop-in solution for caching conversation (solve the 'first send takes several minutes' issue)
- [ ] Incorporate/Polish [Alex's Batch Sending work]()
- [ ] Logging/error messages sufficient for external devs to self-service problems
- [ ] Update documentation

**Comment by bwcDvorak** [comment]
The original thread where we discussed doing this work [is located here]([Original thread/discussion](https://xmtp-labs.slack.com/archives/C06QVLCR8E9/p1711473439535609)).
